# Generated by Django 6.0.3 on 2026-03-28 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='estimated_annual_school_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total school-year cost (tuition, fees, housing, books).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_summary',
            field=models.TextField(blank=True, help_text='Short text for scholarship matching (achievements, leadership, etc.).'),
        ),
    ]
