services:
  db:
    image: postgres:15
    container_name: app_db
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    container_name: app_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PLAID_CLIENT_ID: 69aca82fa35e23000d87b7c8
      PLAID_SECRET: 566fe946099ea72718d1b7b0a75536

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app_frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5174:5174"
    depends_on:
      - backend

volumes:
  postgres_data: