# Generated by Django 6.0.2 on 2026-02-24 07:08

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(default='UOFT_AWARD_EXPLORER', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('offered_by', models.CharField(max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('award_type', models.CharField(blank=True, choices=[('admissions', 'Admissions'), ('in_course', 'In-course'), ('graduating', 'Graduating')], max_length=20, null=True)),
                ('open_to_domestic', models.BooleanField(default=False)),
                ('open_to_international', models.BooleanField(default=False)),
                ('nature_academic_merit', models.BooleanField(default=False)),
                ('nature_athletic_performance', models.BooleanField(default=False)),
                ('nature_community', models.BooleanField(default=False)),
                ('nature_financial_need', models.BooleanField(default=False)),
                ('nature_leadership', models.BooleanField(default=False)),
                ('nature_indigenous', models.BooleanField(default=False)),
                ('nature_black_students', models.BooleanField(default=False)),
                ('nature_other', models.BooleanField(default=False)),
                ('application_required', models.BooleanField(default=False)),
                ('application_url', models.CharField(max_length=300, null=True)),
                ('amount_text', models.CharField(max_length=200, null=True)),
                ('amount_min', models.IntegerField(blank=True, null=True)),
                ('amount_max', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateField(null=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['deadline'], name='scholarship_deadlin_f24616_idx'), models.Index(fields=['award_type'], name='scholarship_award_t_3cc070_idx'), models.Index(fields=['open_to_domestic'], name='scholarship_open_to_b39f30_idx'), models.Index(fields=['open_to_international'], name='scholarship_open_to_fd2276_idx')],
                'unique_together': {('title', 'offered_by')},
            },
        ),
    ]
