# Generated by Django 6.0.2 on 2026-02-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='nature_extracurriculars',
            field=models.BooleanField(default=False),
        ),
    ]
