# Generated by Django 6.0.2 on 2026-02-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_scholarship_nature_extracurriculars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='offered_by',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
