# Generated by Django 6.0.2 on 2026-02-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarship_offered_by_alter_scholarship_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='amount_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='application_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
