# Generated by Django 6.0.2 on 2026-02-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0004_alter_scholarship_amount_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='application_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='award_type',
            field=models.CharField(blank=True, choices=[('admissions', 'Admissions'), ('in_course', 'In-course'), ('graduating', 'Graduating')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
