# Generated by Django 6.0.3 on 2026-03-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0007_savedscholarship_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scholarship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='deadline_is_estimated',
            field=models.BooleanField(default=False, help_text='True when deadline was assumed (e.g. April 30) because source had none.'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False when not seen in last catalog ingest for this level.'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='student_level',
            field=models.CharField(choices=[('undergrad', 'Undergraduate'), ('grad', 'Graduate')], db_index=True, default='undergrad', max_length=16),
        ),
        migrations.AlterField(
            model_name='savedscholarship',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved / Planned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('awarded', 'Awarded'), ('not_awarded', 'Not awarded')], default='saved', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['student_level', 'is_active'], name='scholarship_student_aafb8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='scholarship',
            constraint=models.UniqueConstraint(fields=('title', 'offered_by', 'student_level'), name='uniq_scholarship_title_offered_by_level'),
        ),
    ]
