# Generated by Django 6.0.3 on 2026-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0008_student_level_and_profile_financial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedscholarship',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved / Planned'), ('in_progress', 'In Progress'), ('submitted', 'Submitted')], default='saved', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline_is_estimated',
            field=models.BooleanField(default=False, help_text='True when deadline was assumed (e.g. April 30) because the source had none.'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='False when no longer present in the last catalog ingest for this level.'),
        ),
    ]
