# Generated by Django 6.0.3 on 2026-03-09 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=100)),
                ('goal_type', models.CharField(choices=[('emergency_fund', 'Emergency Fund'), ('tuition', 'Tuition'), ('travel', 'Travel'), ('laptop', 'Laptop'), ('other', 'Other')], default='other', max_length=50)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('target_date', models.DateField()),
                ('risk_level', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('growth', 'Growth')], default='balanced', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(default='My Practice Portfolio', max_length=100)),
                ('portfolio_type', models.CharField(choices=[('system', 'System Generated'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('expected_annual_return', models.DecimalField(decimal_places=2, default=6.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_portfolios', to='investments.investmentgoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticePortfolioHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('etf', 'ETF'), ('stock', 'Stock'), ('bond', 'Bond'), ('cash', 'Cash'), ('other', 'Other')], default='etf', max_length=20)),
                ('allocation_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_annual_return', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investments.practiceportfolio')),
            ],
        ),
    ]
