# Generated by Django 6.0.3 on 2026-03-26 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentgoal',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='practiceportfolio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='practiceportfolioholding',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='goal_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='goal_type',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('tuition', 'Tuition'), ('travel', 'Travel'), ('emergency_fund', 'Emergency Fund'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='investmentgoal',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='practiceportfolio',
            name='expected_annual_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='practiceportfolio',
            name='portfolio_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='practiceportfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('system', 'System'), ('custom', 'Custom')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='practiceportfolioholding',
            name='asset_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='practiceportfolioholding',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('bond', 'Bond'), ('cash', 'Cash')], default='stock', max_length=20),
        ),
        migrations.AlterField(
            model_name='practiceportfolioholding',
            name='expected_annual_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='MLRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(default='stock', max_length=20)),
                ('recommendation_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('risk_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommendation_score'],
            },
        ),
    ]
