# Generated by Django 6.0.3 on 2026-03-26 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investmentgoal_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlrecommendation',
            name='asset_type',
            field=models.CharField(default='etf', max_length=20),
        ),
        migrations.AlterField(
            model_name='practiceportfolioholding',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('etf', 'ETF'), ('bond', 'Bond'), ('cash', 'Cash')], default='etf', max_length=20),
        ),
        migrations.AddIndex(
            model_name='investmentgoal',
            index=models.Index(fields=['user', 'created_at'], name='investments_user_id_caf9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mlrecommendation',
            index=models.Index(fields=['user', 'recommendation_score'], name='investments_user_id_00f25b_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceportfolio',
            index=models.Index(fields=['user', 'goal'], name='investments_user_id_e4cc7a_idx'),
        ),
        migrations.AddIndex(
            model_name='practiceportfolioholding',
            index=models.Index(fields=['portfolio', 'symbol'], name='investments_portfol_d19dbb_idx'),
        ),
    ]
