# Generated by Django 6.0.2 on 2026-02-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Codes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("company", models.CharField(max_length=20)),
                ("desc", models.TextField()),
                ("code", models.URLField()),
            ],
        ),
    ]
