# Generated by Django 6.0.2 on 2026-02-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codes',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='codes',
            name='code',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
