# Generated by Django 6.0.3 on 2026-03-26 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_codes', '0002_codes_url_alter_codes_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codes',
            options={'ordering': ['-popularity_score', 'source_rank', 'company']},
        ),
        migrations.AddField(
            model_name='codes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codes',
            name='external_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codes',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='codes',
            name='in_store',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codes',
            name='in_store_code',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='codes',
            name='is_spc_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codes',
            name='logo',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='codes',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='codes',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codes',
            name='popularity_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codes',
            name='source',
            field=models.CharField(choices=[('spc', 'SPC'), ('unidays', 'UNiDAYS')], db_index=True, default='spc', max_length=20),
        ),
        migrations.AddField(
            model_name='codes',
            name='source_rank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='codes',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='codes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='codes',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='codes',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='codes',
            name='desc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='codes',
            name='url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='codes',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_student_code_source_external_id'),
        ),
    ]
