# Generated by Django 6.0.3 on 2026-03-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_codes', '0003_alter_codes_options_codes_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='source',
            field=models.CharField(choices=[('spc', 'SPC'), ('unidays', 'UNiDAYS'), ('studentbeans', 'Student Beans')], db_index=True, default='spc', max_length=20),
        ),
    ]
