# Generated by Django 6.0.3 on 2026-03-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_id", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("official_name", models.CharField(blank=True, max_length=255)),
                ("account_type", models.CharField(blank=True, max_length=100)),
                ("subtype", models.CharField(blank=True, max_length=100)),
                ("mask", models.CharField(blank=True, max_length=10)),
                ("current_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("available_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("limit_balance", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("currency_code", models.CharField(blank=True, default="USD", max_length=10)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bank_accounts", to="transactions.plaiditem")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name="bankaccount",
            constraint=models.UniqueConstraint(fields=("user", "account_id"), name="uniq_bank_account_user_account_id"),
        ),
    ]
