# Generated by Django 6.0.3 on 2026-03-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_plaiditem_user_bankaccount_and_tx_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
