# Generated by Django 6.0.3 on 2026-03-26 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_key', models.CharField(max_length=255)),
                ('merchant_name', models.CharField(blank=True, default='', max_length=255)),
                ('account_id', models.CharField(blank=True, default='', max_length=255)),
                ('is_recurring', models.BooleanField(default=False)),
                ('dismissed_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'merchant_key', 'account_id'), name='uniq_recurringmerchant_user_merchant_key_account_id')],
            },
        ),
    ]
