# Generated by Django 6.0.3 on 2026-03-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spending", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurringmerchant",
            name="dismissed_after",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
